### ISSUE TITLE
remove_bad.py

### ISSUE THREAD

**Issue by Bird-NZ** [ProGamerGov/dream-creator#22]
The readme talk about a script called remove_bad.py in "data_tools/remove_bad.py" Is this now called "find_bad.py"?
Thx.

**Comment by ProGamerGov** [comment]
@Bird-NZ Yeah, it's the same script! I just forgot to change the name in the main ReadMe: https://github.com/ProGamerGov/dream-creator/tree/master/data_tools#corrupt-image-detector--remover
