### ISSUE TITLE
Support for dream-creator models in neural-dream

### ISSUE THREAD

**Issue by Bird-NZ** [ProGamerGov/dream-creator#23]
I want to build my own models using Dream Creator and use them with neural-dream

In the dream-creator-support branch you here:
https://github.com/ProGamerGov/dream-creator/wiki/How-to-support-Dream-Creator-models-in-other-projects
you say _"Models only require the inceptionv1_caffe.py from the utils directory/folder and can be loaded like this:"_

Can you explain in more detail what this actually means? Do I use the inceptionv1_caffe.py from dream-creater? or do I edit the one in neural-dream. In short how do I use this? Thx!
Mat

**Comment by ProGamerGov** [comment]
@Bird-NZ That's only for other projects. neural-dream was setup to support the models on a separate branch: https://github.com/ProGamerGov/neural-dream/tree/dream-creator-support

**Comment by Bird-NZ** [comment]
Appreciate the help, I can not use models crated with dream-creator and deploy them using neural-dream.
